
```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
```

```{r}
data_unfiltered <- read.csv("../data/ball_by_ball_ipl_2008_2023.csv") %>% 
  filter(Innings == 2) %>% 
  group_by(Match.ID) %>% 
  summarise(rows = sum(Innings.Runs > Target.Score)) %>% 
  filter(rows > 1) %>% 
  select(Match.ID, rows)
```

```{r}
data <- read.csv("../data/ball_by_ball_ipl_2008_2023.csv") %>% 
  filter(Match.ID != 733971 & Match.ID != 1136566 & Match.ID != 1136592 & 
         Match.ID != 980999 & Match.ID != 829803 & Match.ID != 598068 & Match.ID != 1359476 & 
           !(Match.ID %in% data_unfiltered$Match.ID)) %>% 
  filter(Innings == 2) %>% 
  group_by(Match.ID) %>% 
  mutate(Total.Balls.Bowled = ((Over-1)*6 + Ball),
         Total.Balls.Bowled = sprintf("%03d",Total.Balls.Bowled),
         Innings.Wickets = sprintf("%02d",Innings.Wickets),
         Total.Runs.Remaining = Target.Score - Innings.Runs,
         Total.Runs.Remaining = ifelse(Total.Runs.Remaining <= 0, 0, Total.Runs.Remaining),
         Total.Runs.Remaining = sprintf("%03d",Total.Runs.Remaining),
         Post.State = paste0(Total.Balls.Bowled,Innings.Wickets,Total.Runs.Remaining),
         Post.State = if_else(str_detect(Extra.Type, "noballs") | str_detect(Extra.Type, "wides"), 
                              paste0(Post.State, "1"), paste0(Post.State, "0")),
         Prev.State = lag(Post.State),
         Prev.State = ifelse(is.na(Prev.State), paste0("00000", sprintf("%03d",Target.Score), "0"), 
                             Prev.State),
         Runs.Scored = as.integer(substring(Prev.State,6,8)) - as.integer(substring(Post.State,6,8)),
         Runs.Scored = sprintf("%01d",Runs.Scored),
         Ball.Count = as.numeric(substring(Post.State, 1, 3)),
         Stage = ifelse(Ball.Count<37, 1, ifelse(Ball.Count > 84, 3, 2)),
         Event = paste0(Wicket, Runs.Scored, substring(Post.State, 9), Stage)) %>% 
  select(Match.ID, Batter, Total.Balls.Bowled, Innings.Wickets, Total.Runs.Remaining, Prev.State, 
         Post.State,Runs.Scored,Stage,Event) %>% 
  ungroup()
```

```{r}
abrupt_end_row_1 <- data.frame(
  Match.ID = 598066,
  Batter = "Retired Hurt",
  Total.Balls.Bowled = "116",
  Innings.Wickets = "10",
  Total.Runs.Remaining = "051",
  Prev.State = "115090510",
  Post.State = "116100510",
  Runs.Scored = "0",
  Stage = 3,
  Event = "1003")

abrupt_end_row_2 <- data.frame(
  Match.ID = 729293,
  Batter = "Retired Hurt",
  Total.Balls.Bowled = "095",
  Innings.Wickets = "10",
  Total.Runs.Remaining = "094",
  Prev.State = "094090940",
  Post.State = "095100940",
  Runs.Scored = "0",
  Stage = 3,
  Event = "1003")

abrupt_end_row_3 <- data.frame(
  Match.ID = 419114,
  Batter = "Retired Hurt",
  Total.Balls.Bowled = "100",
  Innings.Wickets = "10",
  Total.Runs.Remaining = "099",
  Prev.State = "099090990",
  Post.State = "100100990",
  Runs.Scored = "0",
  Stage = 3,
  Event = "1003")

data_added <- data %>% 
  bind_rows(abrupt_end_row_1, abrupt_end_row_2, abrupt_end_row_3)
```

```{r}
final_data <- data_added %>% 
  group_by(Event) %>%
  mutate(Event.Count = n()) %>%
  ungroup() %>%
  group_by(Stage) %>% 
  mutate(Total.Count = n()) %>% 
  ungroup() %>% 
  mutate(Event.Prob = Event.Count / Total.Count) %>% 
  select(Match.ID, Batter, Total.Balls.Bowled, Innings.Wickets, Total.Runs.Remaining, Prev.State, Post.State, 
         Runs.Scored, Stage,Event, Event.Prob)
```

```{r}
transition_prob <- final_data %>% 
  distinct(Prev.State, Post.State, Event, Event.Prob) 
```

```{r}
first_part <- sprintf("%03d", 0:120) 
second_part <- sprintf("%02d", 0:10)  
third_part <- sprintf("%03d", 0:300)
fourth_part <- sprintf("%01d", 0:1)

terminal_states <- expand.grid(First = first_part, Second = second_part, Third = third_part, 
                               Fourth = fourth_part) %>% 
  mutate(state = paste0(First,Second,Third,Fourth),
         terminal = ifelse((First == "120" & Fourth == "0") | 
                             Second == "10" |
                             Third == "000", 1, 0)) %>% 
  select(state, terminal)
```

```{r}
transition_prob_with_reward <- transition_prob %>%
  mutate(reward = ifelse(substring(Post.State, 6,8) == "000", 1, 0))
```

```{r}
value_initial <- terminal_states %>%
  mutate(value = 0) %>%
  select(state, value)
```

```{r}
value_terminal <- value_initial %>% 
  left_join(terminal_states, by="state") %>% 
  filter(terminal == 1) %>% 
  select(state, value)
```

```{r}
value_previous <- value_initial
max_delta <- Inf
threshold <- 1e-9
count = 0

while(max_delta > threshold) { 

  value <- transition_prob_with_reward %>% 
    left_join(value_previous, by = c("Post.State" = "state")) %>% 
    group_by(state = Prev.State) %>% 
    summarize(value = weighted.mean(reward + value, w = Event.Prob)) %>% 
    bind_rows(value_terminal)

  max_delta <- value_previous %>% 
    inner_join(value, by = "state", suffix = c("_before", "_after")) %>% 
    summarize(max_delta = max(abs(value_before - value_after))) %>% 
    with(max_delta)     
  count = count + 1
  print(max_delta)   
  print(count)
  value_previous <- value }

value
```

```{r}
batter_summary <- final_data %>% 
  left_join(value, by = c("Prev.State" = "state")) %>% 
  rename(win_prob_prev = value) %>% 
  left_join(value, by = c("Post.State" = "state")) %>% 
  rename(win_prob_post = value) %>%
  mutate(
    reward = ifelse(substring(Post.State, 6,8) == "000", 1, 0),
    win_prob_prev = as.numeric(win_prob_prev),
    win_prob_post = as.numeric(win_prob_post),
    win_prob_post = if_else(substring(Post.State, 6,8) == "000", 1, win_prob_post),
    Total.Balls.Bowled = as.numeric(substring(Post.State, 1, 3)),
    Total.Runs.Remaining = as.numeric(substring(Post.State, 6, 8)),
    req_run_rate_post = (Total.Runs.Remaining/(120-Total.Balls.Bowled))*6,
    req_run_rate_pre = (as.numeric(substring(Prev.State, 6, 8))/(120 - as.numeric(substring(Prev.State, 1, 3))))*6,
    win_prob_diff = win_prob_post - win_prob_prev,
    req_run_rate_diff = req_run_rate_post - req_run_rate_pre,
    wicket_event = ifelse(substring(Event, 1, 1) == "1", 1, 0),
    simple_event = ifelse(wicket_event == 1, "Wicket", as.character(Runs.Scored))
  ) %>%
  mutate(
    Stage.Difficulty = case_when(
      win_prob_prev < 0.1 ~ "very_hard",
      win_prob_prev >= 0.1 & win_prob_prev < 0.5 ~ "hard",
      win_prob_prev >= 0.5 & win_prob_prev < 0.9 ~ "easy",
      win_prob_prev >= 0.9 ~ "very_easy",
      TRUE ~ "unknown"
    )    
  ) %>% 
  # filter(win_prob_prev != 0) %>%
  group_by(Prev.State) %>% 
  mutate(
    n_state_events = n()
  ) %>% 
  ungroup() %>% 
  group_by(Match.ID, Batter) %>% 
  mutate(
    Entry.Req.Run.Rate = first(req_run_rate_pre),
    Entry.Total.Ball.Bowled = first(as.numeric(substring(Prev.State, 1, 3))),
    Entry.Win.Prob = first(win_prob_prev),
    Exit.Win.Prob = last(win_prob_post)
  ) %>% 
  mutate(
    Entry.Stage = case_when(
      Entry.Total.Ball.Bowled <= 36 ~ "start",
      Entry.Total.Ball.Bowled >= 37 & Entry.Total.Ball.Bowled <= 84 ~ "middle",
      Entry.Total.Ball.Bowled >= 85 ~ "end",
      TRUE ~ "unknown"
    ),
    Entry.Difficulty = case_when(
      Entry.Win.Prob < 0.1 ~ "very_hard",
      Entry.Win.Prob >= 0.1 & Entry.Win.Prob < 0.5 ~ "hard",
      Entry.Win.Prob >= 0.5 & Entry.Win.Prob < 0.9 ~ "easy",
      Entry.Win.Prob >= 0.9 ~ "very_easy",
      TRUE ~ "unknown"
    ),
  ) %>%
  ungroup()
```

```{r}
batter_match_summary <- batter_summary %>% 
  group_by(Match.ID, Batter, Entry.Stage, Entry.Difficulty) %>% 
  summarise(
    n_balls = n(),
    Entry.Exit.Win.Prob.Diff = first(Exit.Win.Prob) - first(Entry.Win.Prob),
    .groups = "drop"
  ) %>% 
  group_by(Batter, Entry.Stage, Entry.Difficulty) %>% 
  summarise(
    Weighted.Entry.Exit.Win.Prob.Diff = weighted.mean(Entry.Exit.Win.Prob.Diff, n_balls),
    .groups = "drop"
  )

top_10_chasers <- batter_summary %>% 
  group_by(Batter, Entry.Difficulty, Entry.Stage) %>% 
  summarize(n_balls = n(),
            n_matches = n_distinct(Match.ID),
            total_win_prob_diff = sum(win_prob_post - win_prob_prev, na.rm = TRUE),
            avg_win_prob_diff = mean(win_prob_post - win_prob_prev, na.rm = TRUE),
            .groups = "drop") %>% 
  left_join(batter_match_summary, by = c("Batter", "Entry.Stage", "Entry.Difficulty")) %>% 
  arrange(-avg_win_prob_diff) %>% 
  filter(Entry.Difficulty == "hard" & Entry.Stage == "start") %>%
  filter(n_balls > 300) %>%
  select(-c(Entry.Difficulty, Entry.Stage))

top_10_chasers %>% 
  gt() %>%
  tab_header(
    title = md("**Win Probability Added (WPA): Entry Difficulty = Hard & Entry Stage = Start**"),
    subtitle = md("Minimum 300 balls faced.")
  ) %>%
  cols_label(
    avg_win_prob_diff = "Avg WPA",
    total_win_prob_diff = "Total WPA"
  ) %>%
  fmt_percent(columns = c(avg_win_prob_diff, total_win_prob_diff), decimals = 2) %>%
  data_color(
    columns = avg_win_prob_diff,
    colors = scales::col_numeric(
      palette = c("red", "white", "green"),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = Weighted.Entry.Exit.Win.Prob.Diff,
    colors = scales::col_numeric(
      palette = c("red", "white", "green"),
      domain = NULL
    )
  ) %>%
  tab_options(
    data_row.padding = px(2), 
    table.font.size = px(12)
  ) %>%
  opt_row_striping()
```

```{r}
analysis_dataset <- final_data %>% 
  left_join(value, by = c("Prev.State" = "state")) %>% 
  rename(win_prob_prev = value) %>% 
  left_join(value, by = c("Post.State" = "state")) %>% 
  rename(win_prob_post = value) %>%
  mutate(
    reward = ifelse(substring(Post.State, 6,8) == "000", 1, 0),
    win_prob_prev = as.numeric(win_prob_prev),
    win_prob_post = as.numeric(win_prob_post),
    win_prob_post = if_else(substring(Post.State, 6,8) == "000", 1, win_prob_post),
    Total.Balls.Bowled = as.numeric(substring(Post.State, 1, 3)),
    Total.Runs.Remaining = as.numeric(substring(Post.State, 6, 8)),
    req_run_rate_post = (Total.Runs.Remaining/(120-Total.Balls.Bowled))*6,
    req_run_rate_pre = (as.numeric(substring(Prev.State, 6, 8))/(120 - as.numeric(substring(Prev.State, 1, 3))))*6,
    win_prob_diff = win_prob_post - win_prob_prev,
    req_run_rate_diff = req_run_rate_post - req_run_rate_pre,
    wicket_event = ifelse(substring(Event, 1, 1) == "1", 1, 0),
    simple_event = ifelse(wicket_event == 1, "Wicket", as.character(Runs.Scored))
  ) %>%
  mutate(
    Stage.Difficulty = case_when(
      win_prob_prev < 0.1 ~ "very_hard",
      win_prob_prev >= 0.1 & win_prob_prev < 0.5 ~ "hard",
      win_prob_prev >= 0.5 & win_prob_prev < 0.9 ~ "easy",
      win_prob_prev >= 0.9 ~ "very_easy",
      TRUE ~ "unknown"
    )    
  ) %>% 
  # filter(win_prob_prev != 0) %>%
  group_by(Prev.State) %>% 
  mutate(
    n_state_events = n()
  ) %>% 
  ungroup() %>% 
  group_by(Match.ID, Batter) %>% 
  mutate(
    Entry.Req.Run.Rate = first(req_run_rate_pre),
    Entry.Total.Ball.Bowled = first(as.numeric(substring(Prev.State, 1, 3))),
    Entry.Win.Prob = first(win_prob_prev),
    Exit.Win.Prob = last(win_prob_post)
  ) %>% 
  mutate(
    Entry.Stage = case_when(
      Entry.Total.Ball.Bowled <= 36 ~ "start",
      Entry.Total.Ball.Bowled >= 37 & Entry.Total.Ball.Bowled <= 84 ~ "middle",
      Entry.Total.Ball.Bowled >= 85 ~ "end",
      TRUE ~ "unknown"
    ),
    Entry.Difficulty = case_when(
      Entry.Win.Prob < 0.1 ~ "very_hard",
      Entry.Win.Prob >= 0.1 & Entry.Win.Prob < 0.5 ~ "hard",
      Entry.Win.Prob >= 0.5 & Entry.Win.Prob < 0.9 ~ "easy",
      Entry.Win.Prob >= 0.9 ~ "very_easy",
      TRUE ~ "unknown"
    ),
  ) %>%
  ungroup()
```

```{r}
plot_df <- analysis_dataset %>% 
  group_by(Stage, Stage.Difficulty, simple_event) %>% 
  summarise(
    n_balls = n(),
    total_win_prob_diff = sum(win_prob_post - win_prob_prev, na.rm = TRUE),
    avg_win_prob_diff = mean(win_prob_post - win_prob_prev, na.rm = TRUE),
    .groups = "drop"
  ) %>% 
  filter(Stage.Difficulty == "hard" & !simple_event %in% c("3", "5", "7"))

ggplot(plot_df, aes(x = factor(simple_event), y = avg_win_prob_diff, fill = factor(Stage))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Avg. Difference in Win Probability for Each Event Across Different Stages",
    subtitle = "0.1 =< Win Probability before the Event < 0.5",
    x = "Event",
    y = "Average Win Probability Difference",
    fill = "Stage"
  ) +
  theme_minimal() +
  theme(
    # face = "bold" makes it bold, hjust = 0.5 centers it
    plot.title = element_text(face = "bold", hjust = 0.5, size = 14),
    # hjust = 0.5 centers the subtitle as well
    plot.subtitle = element_text(hjust = 0.5, size = 11, italic = TRUE)
  )
```


